"""
================================================================================
TEST QUERY SCRIPT - Test RAG Pipeline Without UI
================================================================================
Quick way to test RAG system with command-line queries.

Usage:
    python scripts/test_query.py "Your question here"
    
    or
    
    python scripts/test_query.py
    # Then enter queries interactively

Author: RAG System
================================================================================
"""

import sys
import os
from pathlib import Path

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from pipeline import RAGPipeline
from llm_handler import get_llm_manager
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


def test_query(query: str):
    """Test a single query."""
    
    print("\n" + "=" * 70)
    print(f"QUERY: {query}")
    print("=" * 70)
    
    try:
        # Initialize
        rag = RAGPipeline(version="v1")
        llm = get_llm_manager()
        
        # Search
        print("\n🔍 Searching...")
        search_result = rag.search(query)
        
        print(f"\n📊 Retrieved {len(search_result.documents)} documents in {search_result.processing_time_ms:.1f}ms")
        
        # Display retrieved documents
        print("\n📄 Retrieved Documents:")
        for i, doc in enumerate(search_result.documents, 1):
            print(f"\n  {i}. Score: {doc.reranker_score:.3f}")
            print(f"     BM25: {doc.bm25_score:.2f}, Vector: {doc.vector_score:.2f}")
            print(f"     Preview: {doc.content[:150]}...")
        
        # Generate response
        print("\n🤖 Generating response...")
        context = rag.get_context(search_result)
        
        response, llm_used = llm.generate(query, context)
        
        print(f"\n✅ Generated by: {llm_used.upper()}")
        print("\n" + "=" * 70)
        print("RESPONSE:")
        print("=" * 70)
        print(response)
        print("=" * 70)
        
    except Exception as e:
        print(f"\n❌ Error: {e}")
        import traceback
        traceback.print_exc()


def main():
    """Main function."""
    
    print("=" * 70)
    print("AYURVEDA RAG - QUERY TESTER")
    print("=" * 70)
    
    if len(sys.argv) > 1:
        # Query from command line argument
        query = " ".join(sys.argv[1:])
        test_query(query)
    else:
        # Interactive mode
        print("\nEnter queries to test (type 'quit' to exit)\n")
        
        while True:
            try:
                query = input("\n📝 Query: ").strip()
                
                if query.lower() in ['quit', 'exit', 'q']:
                    print("\nGoodbye! 👋")
                    break
                
                if not query:
                    print("Please enter a query")
                    continue
                
                test_query(query)
                
            except KeyboardInterrupt:
                print("\n\nGoodbye! 👋")
                break
            except Exception as e:
                print(f"Error: {e}")
                continue


if __name__ == "__main__":
    main()
